### ISSUE TITLE
Running in a loop issue - losing workspace

### ISSUE THREAD

**Issue by RichardScottOZ** [MiraGeoscience/geoapps#179]
This one is odd:-

I have a loop (@domfournier  knows this one)

Running a small inversion, move onto the next

and get 

```python
Running Inversion
model has any nan: 0
=============================== Projected GNCG ===============================
  #     beta     phi_d     phi_m       f      |proj(x-g)-x|  LS    Comment   
-----------------------------------------------------------------------------
   0  1.28e+11  4.99e+09  2.21e-02  7.81e+09    1.34e+02      0              
  3%|▎         | 2746/87957 [06:21<3:17:14,  7.20it/s]
Traceback (most recent call last):
  File "C:\Users\rscott\OneDrive - OZ Minerals\FunctionMiraLU.py", line 757, in <module>
    mrec, inv_group = run_inversion("Inversion_equivalent_source_REF", grav_survey, simulation, reference_model=ref_model)
  File "C:\Users\rscott\OneDrive - OZ Minerals\FunctionMiraLU.py", line 532, in run_inversion
    mrec = inv.run(m0)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\utils\counter_utils.py", line 105, in wrapper
    out = f(self, *args, **kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\inversion.py", line 66, in run
    self.m = self.opt.minimize(self.invProb.evalFunction, self.invProb.model)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\utils\counter_utils.py", line 105, in wrapper
    out = f(self, *args, **kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\optimization.py", line 398, in minimize
    self.doEndIteration(xt)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\utils\counter_utils.py", line 93, in wrapper
    out = f(self, *args, **kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\utils\code_utils.py", line 178, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\optimization.py", line 701, in doEndIteration
    self.callback(xt)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\inversion.py", line 72, in _optCallback
    self.directiveList.call("endIter")
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\directives.py", line 190, in call
    getattr(r, ruleType)()
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\SimPEG\directives.py", line 1036, in endIter
    data = self.h5_object.add_data(
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\objects\object_base.py", line 137, in add_data
    data_object = self.workspace.create_entity(
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\workspace\workspace.py", line 307, in create_entity
    created_entity = self.create_data(
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\workspace\workspace.py", line 276, in create_data
    created_entity = member(data_type, **entity_kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\data\float_data.py", line 29, in __init__
    super().__init__(data_type, **kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\data\numeric_data.py", line 30, in __init__
    super().__init__(data_type, **kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\data\data.py", line 48, in __init__
    super().__init__(**kwargs)
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\shared\entity.py", line 55, in __init__
    setattr(self, "parent", kwargs["parent"])
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\shared\entity.py", line 249, in parent
    if self.parent is not None:
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\shared\entity.py", line 262, in parent
    self._parent = self.workspace.root
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\shared\entity.py", line 356, in workspace
    return self.entity_type.workspace
  File "C:\Users\rscott\AppData\Local\Continuum\anaconda3\envs\geoapps\lib\site-packages\geoh5py\shared\entity_type.py", line 166, in workspace
    assert workspace is not None
AssertionError
```

which is strange - it actually writes the iteration 0 to the geoh5 workspace ok - then fails - the first run works fine and writes to workspace, this is the second run through (which writes to another workspace - e.g. if 2745 in the first one, 2746 if the next one exists).

If it couldn't find it would have thought the first one would fail so something happening to lose inside that - or with a previous ws existing?  Not debugged at all yet.

All precreated workspaces, too.

**Comment by RichardScottOZ** [comment]
So from entity_type, definitely:-
```python
Workspace is: <geoh5py.workspace.workspace.Workspace object at 0x000001E25DEE43A0>
Workspace is: None
```

**Comment by RichardScottOZ** [comment]
```python
__exception__ = {tuple: 3} (<class 'AssertionError'>, AssertionError(), <traceback object at 0x00000171E78F6E00>)
self = {DataType} <geoh5py.data.data_type.DataType object at 0x00000171E50C4370>
workspace = {NoneType} None
```

**Comment by RichardScottOZ** [comment]
Sure... just not small in that sense, will see what I can do... pretty much that Inversion Workflow with reference model.. and the second time in a loop it is crashing in the first equivalent part.

**Comment by domfournier** [comment]
yea sorry, I ll get to it tomorrow. True, could be an access right if the threads are trying to write at the same time. Might have to re-structure the run...

**Comment by domfournier** [comment]
@RichardScottOZ did you get to the bottom of this?

**Comment by RichardScottOZ** [comment]
No, not yet sorry, haven't had time to re-delve into debugging a lower level than I had got to as yet as above.  So I have to investigate more

When I did the big job ran each one literally in a separate container.

**Comment by RichardScottOZ** [comment]
It was breaking at a particular point in the directives.

**Comment by domfournier** [comment]
Most likely on the SaveGeoh5 directives.

**Comment by RichardScottOZ** [comment]
Yeah, it was as I recall - but I hadn't worked it why it was losing it at that point.
