### ISSUE TITLE
ImportError: cannot import name 'create_nested_mesh' from 'SimPEG.utils.drivers' 

### ISSUE THREAD

**Issue by geophylika** [MiraGeoscience/geoapps#274]
Run SimPEG DC&IP 3D Inversion or another data inversion as Online Documentation,with error bellow:
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\geoapps\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "d:\ProgramData\Anaconda3\envs\geoapps\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "d:\geoapps-develop\geoapps\drivers\__init__.py", line 8, in <module>
    from . import components
  File "d:\geoapps-develop\geoapps\drivers\components\__init__.py", line 8, in <module>
    from .data import InversionData
  File "d:\geoapps-develop\geoapps\drivers\components\data.py", line 25, in <module>
    from SimPEG.utils.drivers import create_nested_mesh
ImportError: cannot import name 'create_nested_mesh' from 'SimPEG.utils.drivers' (d:\ProgramData\Anaconda3\envs\geoapps\lib\site-packages\SimPEG\utils\drivers\__init__.py)

How can I fix it?

**Comment by domfournier** [comment]
Hi @geophylika,

This sounds like an installation issue with simpeg. 
Try the following:
1- Open an anaconda terminal.
2- Run: **conda activate geoapps**
3- Run: **pip install git+https://github.com/MiraGeoscience/simpeg.git@release/geoapps-0.6.2**
4- Re-start the apps and run again.

Let us know how this goes.

**Comment by domfournier** [comment]
@geophylika 
Can we close this?
